### ISSUE TITLE
Fails to launch in vanilla CKAN 2.2

### ISSUE THREAD

**Issue by davidmegginson** [okfn/ckanext-issues#12]
I installed following instructions in a vanilla instance of CKAN 2.2, and got the following error:

```
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/ckanext/issues/model.py", line 9, in <module>
    from ckan.model.meta import types, Table, ForeignKey, DateTime
ImportError: cannot import name types
```

Missing dependency?

**Comment by rgrp** [comment]
FIXED. Def working with v2.2 and v2.3 when we last looked.
